### ISSUE TITLE
Tokenisation error 

### ISSUE THREAD

**Issue by abhigoku10** [llmbev/talk2bev#1]
@Vikr-182 @RudeNinja  Thanks for sharing the code base i am getting the following error when i try to  execute the code . Can you please let me knw the solution Thanks in advance 

2023-11-16 06:56:27.421900: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered 2023-11-16 06:56:27.421962: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered 2023-11-16 06:56:27.422005: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered 2023-11-16 06:56:30.670605: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT Initializing Chat Traceback (most recent call last):   File "/content/drive/MyDrive/talk2bev/talk2bev/talk2bev/click2chat/click2chat_llava.py", line 179, in <module>     tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, True, True)   File "/content/drive/MyDrive/talk2bev/talk2bev/talk2bev/click2chat/llava/model/builder.py", line 105, in load_pretrained_model     tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False, trust_remote_code=True)   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 718, in from_pretrained     tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 663, in __getitem__     model_type = self._reverse_config_mapping[key.__name__] KeyError: 'LlavaConfig'

**Comment by Vikr-182** [comment]
Hi @abhigoku10 
Can you check the version of LLaVa you are using? We had used [LLava-v1.1-vicuna-13b-v1.3](https://huggingface.co/liuhaotian/llava-v1-0719-336px-lora-merge-vicuna-13b-v1.3)
This maybe helpful: https://github.com/haotian-liu/LLaVA/issues/586.

Let me know!
